### ISSUE TITLE
component class is missing

### ISSUE THREAD

**Issue by MaGiCmAsTeR0511** [naffiq/yii2-twitter-api#1]
you have to set an class in the component you don't have a class !!???

`<?php
return [
    // Your app settings ...
    'components' => [
        // Other components ...
        'twitter' => [
  **class => ??????**
            'oauthAccessToken' => 'YOUR_OAUTH_ACCESS_TOKEN',
            'oauthAccessTokenSecret' => 'YOUR_OAUTH_ACCESS_TOKEN',
            'consumerKey' => 'YOUR_CONSUMER_KEY',
            'consumerSecret' => 'YOUR_CONSUMER_SECRET'
        ]        
    ]
    // ...
];`

**Comment by naffiq** [comment]
Forgot to include this in the doc:
```php
<?php
return [
    // Your app settings ...
    'components' => [
        // Other components ...
        'twitter' => [
            'class' => 'naffiq\twitterapi\TwitterAPI',
            'oauthAccessToken' => 'YOUR_OAUTH_ACCESS_TOKEN',
            'oauthAccessTokenSecret' => 'YOUR_OAUTH_ACCESS_TOKEN',
            'consumerKey' => 'YOUR_CONSUMER_KEY',
            'consumerSecret' => 'YOUR_CONSUMER_SECRET'
        ]        
    ]
    // ...
];
```

This should be working

**Comment by MaGiCmAsTeR0511** [comment]
thx
